[status]
overall = { fg = "black"}
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

[mode]
normal_alt = {fg = "blue", bg = "darkgrey"}
select_main = {bg = "magenta",fg = "black"}
select_alt = {fg = "magenta",bg = "darkgrey"}
unset_alt = {fg = "red", bg = "darkgrey"}

[indicator]
padding  = {open= "█", close= "█"}
